defaults:
  - algo@rolf: skimo
  - env: kitchen
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

env:
  task: base

rolf:
  env: kitchen
  reward_scale: 1
  num_units: 128
  num_layers: 4
  state_dim: 256
  log_std: true
  lstm: true
  pretrain:
    data_path: data/kitchen.gz
    split: {train: 0.99, val: 0.01, test: 0.0}
    batch_size: 512
    log_every: 100
    evaluate_every: 500
    ckpt_every: 5000
  target_divergence: 5
  min_std: 0.01
  use_prior: true
  fixed_alpha: 0.5
  batch_size: 256
  scalars:
    ll_actor: 2

# Training
deterministic: false
seed: 0
is_train: true
init_ckpt_path: null
init_ckpt_pretrained: false
gpu: null
pretrain: true
pretrain_max_step: 1e6

# Evaluation
ckpt_num: null
num_eval: 1
record_video: true
record_video_caption: true
record_demo: false

# Log
run_prefix: null
notes: null
log_root_dir: log
wandb: false
wandb_entity: null
wandb_project: null

# Hydra
hydra:
  output_subdir: null
  run:
    dir: .
