defaults:
  - algo@rolf: spirl_tdmpc
  - env: maze
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

rolf:
  env: maze
  hl_horizon: 15
  pretrain:
    data_path: data/maze.gz
    batch_size: 512
  target_divergence: 1

# Training
deterministic: false
seed: 0
is_train: true
init_ckpt_path: null
init_ckpt_pretrained: false
gpu: null

# Evaluation
ckpt_num: null
num_eval: 1
record_video: true
record_video_caption: true
record_demo: false

# Log
run_prefix: null
notes: null
log_root_dir: log
wandb: false
wandb_entity: null
wandb_project: null

# Hydra
hydra:
  output_subdir: null
  run:
    dir: .
