defaults:
  - algo@rolf: spirl
  - env: maze
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

# Training
deterministic: false
seed: 0
is_train: true
init_ckpt_path: null
init_ckpt_pretrained: false
ckpt_num: null
gpu: null
optimizer: radam

# Evaluation
num_eval: 1
record_video: true
record_video_caption: true
record_demo: false

# Log
log_output_per_epoch: 100  # log the non-image/video outputs N times per epoch
log_images_per_epoch: 4    # log images/videos N times per epoch
run_prefix: null
notes: null
log_root_dir: log
wandb: false
wandb_entity: null
wandb_project: null

# Hydra
hydra:
  output_subdir: null
  run:
    dir: .
