defaults:
  - common
  - _self_

name: spirl

warm_up_step: 5000
max_global_step: 2e6 
n_steps_per_update: 1  # number of env steps collected per policy update

log_every: 100
evaluate_every: 5000
ckpt_every: 1e5
sampler_init_every: 1e5

sampler_config:
  n_frames: 1

