defaults:
  - algo@rolf: tdmpc
  - env: default
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout


env:
  id: dm.quadruped.walk
  screen_size: [64, 64]
  action_repeat: 2
  frame_stack: 3
  absorbing_state: false
  pixel_ob: false
  state_ob: true

rolf:
  max_global_step: 500000

# Training
seed: 0
is_train: true
init_ckpt_path: null
init_ckpt_pretrained: false
gpu: null

# Evaluation
ckpt_num: null
num_eval: 1
record_video: true
record_video_caption: true
record_demo: false

# Log
run_prefix: null
notes: null
log_root_dir: log
wandb: false
wandb_entity: null
wandb_project: null

# Hydra
hydra:
  output_subdir: null
  run:
    dir: .
